export const ADD_COMMAND = 'ADD_COMMAND';
export const ADD_CONTAINER = 'ADD_CONTAINER';
export const DELETE_CONTAINER = 'DELETE_CONTAINER';
export const MOVE_COMMAND = 'MOVE_COMMAND';
export const EDIT_CONTAINER = 'EDIT_CONTAINER';
export const CHANGE_CONTAINER_ID = 'CHANGE_CONTAINER_ID';
export const EXTEND_CONTAINER = 'EXTEND_CONTAINER';

export const LOAD_TRIGGER_DEFINITIONS = 'LOAD_TRIGGER_DEFINITIONS';
export const LOAD_TRIGGER = 'LOAD_TRIGGER';
export const SAVE_TRIGGER = 'SAVE_TRIGGER';
export const DELETE_TRIGGER = 'DELETE_TRIGGER';
export const SELECT_TRIGGER = 'SELECT_TRIGGER';
export const EDIT_TRIGGER = 'EDIT_TRIGGER';
export const NEW_TRIGGER = 'NEW_TRIGGER';

export const LOAD_NODES = 'LOAD_NODES';
